services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/Users/brian/Documents/programming/docker/airbnb
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/Users/brian/Documents/programming/docker/airbnb
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/Users/brian/Documents/programming/docker/airbnb
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/Users/brian/Documents/programming/docker/airbnb
  mongo:
    image: arm64v8/mongo:latest
    ports:
      - '27017:27017'
